[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install --assume-yes libwayland-dev:arm64 wayland-protocols libxkbcommon-dev:arm64 libfontconfig1-dev:arm64"
]